#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-comtypes
Version  : 1.1.11
Release  : 7
URL      : https://files.pythonhosted.org/packages/a6/5f/8819e096affc09a931b89d86204aac7d5e0afa25012918da92d20253dbc2/comtypes-1.1.11.zip
Source0  : https://files.pythonhosted.org/packages/a6/5f/8819e096affc09a931b89d86204aac7d5e0afa25012918da92d20253dbc2/comtypes-1.1.11.zip
Summary  : Pure Python COM package
Group    : Development/Tools
License  : MIT
Requires: pypi-comtypes-bin = %{version}-%{release}
Requires: pypi-comtypes-license = %{version}-%{release}
Requires: pypi-comtypes-python = %{version}-%{release}
Requires: pypi-comtypes-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
========
        
        **comtypes** is a lightweight Python COM package, based on the ctypes_
        FFI library, in less than 10000 lines of code (not counting the
        tests).
        
        **comtypes** allows to define, call, and implement custom and
        dispatch-based COM interfaces in pure Python.  It works on Windows and
        64-bit Windows. Windows CE support was dropped since comtypes==1.1.8.

%package bin
Summary: bin components for the pypi-comtypes package.
Group: Binaries
Requires: pypi-comtypes-license = %{version}-%{release}

%description bin
bin components for the pypi-comtypes package.


%package license
Summary: license components for the pypi-comtypes package.
Group: Default

%description license
license components for the pypi-comtypes package.


%package python
Summary: python components for the pypi-comtypes package.
Group: Default
Requires: pypi-comtypes-python3 = %{version}-%{release}

%description python
python components for the pypi-comtypes package.


%package python3
Summary: python3 components for the pypi-comtypes package.
Group: Default
Requires: python3-core
Provides: pypi(comtypes)

%description python3
python3 components for the pypi-comtypes package.


%prep
%setup -q -n comtypes-1.1.11
cd %{_builddir}/comtypes-1.1.11

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649730428
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-comtypes
cp %{_builddir}/comtypes-1.1.11/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-comtypes/47723c8cb01651fd9be8d8d9107dd0666b4244eb
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/clear_comtypes_cache.py

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-comtypes/47723c8cb01651fd9be8d8d9107dd0666b4244eb

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
